Descripción del proyecto
marcosrmartin/PerroAndaluz pull request #1
Opened 2022-09-18 11:14 UTC by marcosrmartin

Definición del proyecto a desarrollar durante la asignatura.

2022-09-20 10:55 UTC, JJ commented
Si no pones la lista de comprobación, es que no la has seguido, y si no la has seguido, es muy posible que haya algún error. Revisaré de todas formas.

2022-09-20 10:57 UTC, JJ requested changes
Por favor, plantea un problema que requiera cierto esfuerzo para la solución. Los problemas tienen una serie de comportamientos que luego se tienen que testear. Si lo único que hay que testear es si el programa divide bien, no es ni siquiera un programa, es una función.

2022-09-20 10:57 UTC, JJ commented on README.md
> +# Respositorio para la asignatura Infraestructura Virtual UGR (22/23)
Repositorio

2022-09-20 10:57 UTC, JJ commented on README.md
> +Con este proyecto crearemos una aplicación para obtener un control sobre como gastamos el dinero, dividir los gastos en conjunto entre amigos, compañeros de piso o parejas y poder realizar una previs
Dividir es una lógica de negocio muy simple. Ni siquiera es una lógica de negocio, es una simple función.

2022-09-23 08:34 UTC, marcosrmartin commented
@JJ Listo para revisión

2022-09-24 08:38 UTC, JJ commented
Por favor, tenéis que seguir la lista de comprobación en cada uno  de los objetivos.

2022-09-24 08:38 UTC, JJ approved these changes
:+1:

2022-09-24 15:05 UTC, merged