Añadido ambos gestores, con sus respectivas configuraciones.
marcosrmartin/PerroAndaluz pull request #17
Opened 2022-11-08 02:22 UTC by marcosrmartin

* [ ]  ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos anteriores?
* [ ]  ¿Se ha desarrollado el fichero para las tareas a partir de un issue?
* [ ]  ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la existencia de herramientas que permitan automatizar tareas?
* [ ]  ¿Hemos justificado correctamente en caso de elegir un gestor de dependencias el que se use como gestor de tareas?
* [ ]  ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes existentes?

2022-11-14 09:22 UTC, JJ requested changes
Por favor, haz todo slos cambios que no correspondan al objetivo en otro lugar.
Consulta también los errores frecuentes de las semanas 8 a la 10

2022-11-14 09:22 UTC, JJ commented on README.md
> +## Elección del gestor de dependencias
No pongáis esto en el README, no forma parte de lo que debe leer quien llegue al proyecto.

2022-11-14 09:22 UTC, JJ commented on README.md
> +Para esta decisión nos hemos basado en esta comparativa entre [npm, yarn, y npmp](https://nicco.io/blog/going-beyond-npm-meet-yarn-pnpm), con la que hemos descartado npmp ya que no está preparada par
Es del 2019; pnpm está más que preparado para producción. En todo caso, los criterios tienes que establecerlos de antemano.

2022-11-14 09:22 UTC, JJ commented on README.md
> +Esta se debe a que npm tiene npx y yarn no, y yarn es más rápido que npm, buscando y gracias a [esta comparativa](https://www.codingninjas.com/codestudio/library/difference-between-npm-and-npx) entre
¿`npx` es un criterio? ¿Por qué?

2022-11-14 09:22 UTC, JJ commented on README.md
> +Para esta elección he comparado entre [gulp y grunt](https://www.keycdn.com/blog/gulp-vs-grunt) ([aqui también](https://deliciousbrains.com/grunt-vs-gulp-battle-build-tools/)), he seleccionado gulp y
Una vez más, primero los criterios, luego las opciones, luego la elección. Hay más opciones que las que listas.

2022-11-14 09:22 UTC, JJ commented on app/gulpfile.js
> +exports.check = parallel(usuario, pago, evento);
Si lo que quieres son procesos en paralelo, es uno de los criterios que tienes que poner.

2022-11-14 09:22 UTC, JJ commented on app/src/services/Evento.js
> +var Pago = require('Pago');
Estos cambios no corresponden al objetivo, y además no siguen las mejores prácticas (antes si lo seguían)

2022-12-02 10:34 UTC, marcosrmartin commented
@JJ Listo para revisión.

2022-12-09 08:06 UTC, JJ approved these changes
👍 Pues tiene buena pinta, a pesar de las objeciones.

2022-12-09 08:06 UTC, JJ commented on docs/readme.md
> +2. Seguridad.
¿Cómo evalúas la seguridad de un gestor de dependencias?

2022-12-09 08:06 UTC, JJ commented on package.json
> +    "check": "node --check ./src/services/evento.js & ./src/services/pago.js & ./src/services/usuario.js"
Esto no funciona. Compruébalo, por favor.

2022-12-09 08:06 UTC, JJ commented on package.json
> +    "start": "npm install yarn -g --save && yarn set version berry && yarn",
`start` se usa normalmente para iniciar una web; en este caso creo the `init` sería más correcto, aunque ese lo usa `npm` internamente; quizás `setup` o algo así.

2022-12-09 08:17 UTC, merged