Milestones e Historias de usuario
marcosrmartin/PerroAndaluz pull request #7
Opened 2022-09-29 14:30 UTC by marcosrmartin

Milestones:
* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto, y no un
   concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ]  ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [ ]  ¿El milestone 0 es mínimo *y* viable?
* [ ]  ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

Historias de usuario:
* [ ] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [ ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ ] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [ ] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2022-09-29 18:31 UTC, JJ requested changes
Los milestones en el texto para que se puedan comentar uno por uno, por favor. Igual con las historias de usuario.

2022-09-30 17:04 UTC, marcosrmartin commented
@JJ Listo para revisión.

2022-09-30 17:48 UTC, JJ requested changes
Por favor, consulta los conceptos relevantes tal como se han explicado hoy, ayer y el viernes pasado en clase. El material está enlazado desde el fichero de esta semana.

2022-09-30 17:48 UTC, JJ commented on README.md
> +Definir la estructura de datos para guardar las cuentas de cada usuario.
No está descrito como un producto. Lo hemos comentado hoy en clase; mira la presentación enlazada desde el material de esta semana.

2022-09-30 17:48 UTC, JJ commented on README.md
> +Definir una API para la gestión de las cuentas de cada usuario.
No se sigue inmediatamente del anterior. Una vez más, consulta el concepto de milestone como se ha explicado hoy en clase.

2022-09-30 17:48 UTC, JJ commented on README.md
> +#### [HU-03] Gestionar desde diferentes dispositivos
No es relevante para la asignatura, ni está relacionado con la lógica de negocio.

2022-10-06 07:43 UTC, marcosrmartin reviewed
Actualización milestones.

2022-10-06 07:44 UTC, marcosrmartin commented
@JJ Listo para revisión.

2022-10-06 08:42 UTC, marcosrmartin reviewed
Update README.md

2022-10-06 08:50 UTC, marcosrmartin commented
@JJ Listo para revisión.

2022-10-06 09:44 UTC, JJ approved these changes
Genéricamente está bien, pero si fueras tan amable de modificar lo que se te ha comentado antes del siguiente objetivo estaría genial.

2022-10-06 09:44 UTC, JJ commented on README.md
> +Módulo definido en un lenguaje y que el mismo compile sin problemas.
Recuerda que esto es un modelo del problema. Hay que especificar las cosas con precisión para que quien las reciba pueda entenderlas.

2022-10-06 09:44 UTC, JJ commented on README.md
> +Implementar en el módulo anterior, las funcionalidades necesarias para la lógica de negocio.
Convendría que lo particularizaras un poco más; puede que no haga falta implementar *todas* las funciones, sólo las correspondientes a una HU.

2022-10-06 09:44 UTC, JJ commented on README.md
> +#### [HU-02] Modificar usuarios en pago
Por ejemplo, esto puede requerir lógica de negocio que no quepa en M1

2022-10-07 08:18 UTC, marcosrmartin commented
@JJ Listo para revisión.

2022-10-07 08:48 UTC, JJ approved these changes
👍

2022-10-07 08:48 UTC, JJ commented
Ya estaba aprobado de todas formas...

2022-10-07 10:50 UTC, merged